### ISSUE TITLE
builtin time does not work

### ISSUE THREAD

**Issue by e70838** [Orc/pdksh#1] opened 2018-09-11 11:15 UTC
$ time -p sleep 5
real     8.33
user     0.00
sys      0.00
$ /usr/bin/time -p sleep 5
real 5.00
user 0.00
sys 0.00

$ echo $KSH_VERSION
@(#)PD KSH v5.2.14 99/07/13.2

I have noticed this issue:
on Red Hat Enterprise Linux Server release 6.8 (Santiago).
and on Red Hat Enterprise Linux Client release 5.8 (Tikanga).

Where should I search ?

**Comment by Orc** [comment] 2018-09-11 13:29
That's interesting; you noticed it only on my version of pd_ksh (it reproduced for me on macos 10.13, didn't reproduce on freebsd 4.11;  I presume it will reproduce on other Linices) or on the standard one as well?

**Comment by e70838** [comment] 2018-09-11 14:34
Yes, the problem occurs on the standard pdksh as well.

**Comment by Orc** [comment] 2018-09-11 17:26
It looks like a clock frequency bug; ksh_times() (aka times()) returns a clock_t in 1/100s of a second, but clocktos() (in c_sh.c) is assuming it's in 1/60th of a second (CLK_TCK is defaulted to 60hz if it can't be found, and it looks like it's being found in missing.c but NOT in c_sh.c)

I should be able to track it down without too much trouble (he says optimistically)

**Comment by Orc** [comment] 2018-09-11 20:46
It's trackable.  I fixed it on macos by checking for the existence of limits.h (that's where OSX puts the definition of CLK_TCK) but need to do some more configure checking to properly pull in time.h (where modern Linices put CLK_TCK) and its prerequisites.

**Comment by Orc** [comment] 2018-09-11 21:40
Linux is, of course, stupid when it comes to CLK_TCK;  CLK_TCK is, because the standards orgs are stupid, now depreciated so it's not defined unless cc is flagged to an older version of the standards.

And times(), of course, returns times in CLK_TCK intervals (or as the times() manpage helpfully suggests, in sysconf(_SC_CLK_TCK).    So much for useful standards.

**Comment by Orc** [comment] 2018-09-12 00:59
Okay, fixed (for values of fixed that are a recent version of centos & a recent version of debian; checking for limits.h fixed it on macos 10.13) and checked into my version of the code.  No actual code changes for this one, just the configuration changes;  check for the existence of limits.h (macos puts CLK_TCK here?) and then check for the CLK_TCK define and if I can't find it and we're on a linux box, check for sysconf(_SC_CLK_TCK) and manually #define CLK_TCK as that if it exists.

So if you use this copy of pdksh, you should be set now.

**Closed as completed by Orc** 2018-09-12 00:59 UTC

**Comment by e70838** [comment] 2018-09-12 11:12
Hello. Your work and comments have been very helpful and fully solved my issue. I just wanted to thank you very much for all your efforts. I am very impressed.
